### ISSUE TITLE
Hotspot Admin

### ISSUE THREAD

**Issue by eeeurico** [Kupiki/Kupiki-Hotspot-Admin-Install#1]
Hello, sorry for making this an issue.
I've installed both the Kupiki Hotspot and the Admin but don't seem to find where and how to access the Kupiki-Hotspot-Admin application.
I have no problem logging into daloRADIUS.
Thank you so much in advance

**Comment by pihomeserver** [comment]
Can you please try the same IP than daloradius but using port 3000 ?

**Comment by eeeurico** [comment]
sorry the delay. Port 3000 works.
Thank you so much!

**Comment by maluherby** [comment]
Hi, may i know how to access the admin back end? thanks

**Comment by pihomeserver** [comment]
There is a node project handle by PM2 running in the kupiki user home folder
