### ISSUE TITLE
Can not log in 

### ISSUE THREAD

**Issue by Syn3rgy94** [Kupiki/Kupiki-Hotspot-Admin-Install#2]
Hello, 
thank you for your great scripts! But i have an issue. 
I've installed the Kupiki Hotspot and the Kupiki-Hotspot-Admin-Install. I can go to the Login Page from the admin frontend but it impossible to log in. 
If I click at the login button with any username/password nothing happend. 
Thank you for your help!

**Comment by pihomeserver** [comment]
admin / admin ?

**Comment by Syn3rgy94** [comment]
I tried this too. But the Log in Button is not clickable. 
When I tried to log in with return after I typed in the password but nothing happend. 
Thank you for your fast response!

**Comment by pihomeserver** [comment]
What browser do you use ? I tested it under Firefox, Chrome and Safari and credentials work

Also do you confirm on the backend folder that a `kupiki.sqlite` database exists ? With a record in the `users` table ?

**Comment by Syn3rgy94** [comment]
I use a Firefox 59.0.2 (64-bit). I've tried it in Microsoft Edge and Chome too. Always the same issue that when I click at "Login" nothing happens. 

Yes, in the backend folder exists the `kupiki.sqlite` database and the table `users` has one entry: admin

**Comment by pihomeserver** [comment]
As root can you please run command
`su - kupiki -c "pm2 list"` ? You should have 2 entries one for backend one for frontend
Welcome in the alpha world :-)

**Comment by Syn3rgy94** [comment]
Yes there are two entries. `Backend` and `frontend`. Both of them are online and are in the mode `fork`.

**Comment by pihomeserver** [comment]
Trying to guess how to debug....
In the browser no error in the console ?
I install all from scratch to check

**Comment by pihomeserver** [comment]
Ok can reproduce 
The config file in the front app still has a wrong IP to connect to the server ... Replace it with the IP of eth0 and restart all (or the pi)
I will update the script.

**Comment by Syn3rgy94** [comment]
Thank you very much. Now it works! 
But now there is an other issue: 
At the Userview will be no users shown. It shows the following message: 
```
Unable to load users
Request failed with status code 500

```

**Comment by pihomeserver** [comment]
check the logs of the backend in the /home/kupiki/.pm2 folder

**Comment by pihomeserver** [comment]
Ok on the Raspberry there is an issue with the ORM used to connect to MariaDB. I work on it

**Comment by pihomeserver** [comment]
connect to your MySql instance from command line then : 
```
use mysql;
update user set authentication_string=password('raspbian'), plugin='mysql_native_password' where user='root';
flush privileges;
```
If needed replace the password by yours if you changed it
Then restart the service and refresh your browser

**Comment by Gxbx** [comment]
Hello,

**Comment by Gxbx** [comment]
Hello,
thank you for your great project, is really awesome! But i have an issue.
I've installed the Kupiki-Hotspot-Admin-Install. but can't log in, reviewing this issue I found that I do not have the kupiki.sqlite file. Maybe you can provide the file or sqlite schema?, i tried execute su - kupiki -c "pm2 list" command but can't find the password.
Thank you for your help!
