### ISSUE TITLE
Frontend will not start after reboot

### ISSUE THREAD

**Issue by arjan1970** [Kupiki/Kupiki-Hotspot-Admin-Install#3]
Hi,

I had the front end working for a while without any issues 
but now I had to reboot the raspberry pi and the hotspot is working, Kupiki and Daloradius both are working. Just the frontend stopped working. 

When I run the command su - kupiki -c "pm2 list" is have the 2 entries, backend and frontend, both are online. Only thing that changed is the ip address of the hotspot (x.x.178.70 to x.x.178.159). When I load http://same ip than daloradius:3000 it says the site can not be loaded and refused connection (ERR_CONNECTION_REFUSED). I can't find any solution here or any where else.

Thanks for the help!!!!

**Comment by pihomeserver** [comment]
Hi
In the Kupiki Admin Frontend folder, in config/config.*.json files change the IP by the new one
Also delete the frontend job in pm2 and create a new one with
```
su - kupiki -c "cd /home/kupiki/Kupiki-Hotspot-Admin-Frontend && HOST='`ip -4 route get 8.8.8.8 | awk {'print $7'} | tr -d '\n'`' pm2 start --name frontend npm -- start"
```
Should do the job until i find a better way to execute the front end

**Comment by arjan1970** [comment]
Thanks, I managed to change the files. However, I am pretty new to this and know the basics but this is a bit too much, how do I delete the frontend job in pm2? I managed to get pm2 job deleted en created the new one. Now it does open in the browser (chrome and safari). But now it does not take the admin/admin login.
Thanks

**Comment by pihomeserver** [comment]
Can you check result of following command : 
```
ip -4 route get 8.8.8.8 | awk {'print $7'} | tr -d '\n'
```
It should return your correct WAN IP (the one with internet / Ethernet one)

Else try next steps

Start with 
```
su - kupiki -c "pm2 list"
```
You should get a list of process managed by pm2. Identify the one for the frontend (should have the name _frontend_)
Then you stop the process with 
```
su - kupiki -c "pm2 stop frontend"
```
And delete it
```
su - kupiki -c "pm2 delete frontend"
```
Then recreate it with the correct IP set before the node job start

**Comment by pihomeserver** [comment]
Can you please open the browser developper console ? And check if any error is displayed ?
Else look at the pm2 logs with
```
su - kupiki -c "pm2 logs frontend"
```
and
```
su - kupiki -c "pm2 logs backend"
```
Also please confirm that both process are running, and that the user admin is created in the Sqlite database

**Comment by arjan1970** [comment]
It's working again. Thanks for the help!!
