### ISSUE TITLE
Errors on install?!

### ISSUE THREAD

**Issue by EasyVoiceTel** [Kupiki/Kupiki-Hotspot-Admin-Install#4]
::: Install default packages
::: Get key for Node repository
::: Add source for Node package
::: Add source for Node package
::: Update repositories list (will add node repo)
::: Installing Node
::: Installing gulp and CLI
::: Create dedicated user kupiki
::: Cloning Backend project
::: Changing rights of backend folder
::: Starting packages installation with npm
::: 
::: Something went wrong with the last command. Please check the log file
::: 
-------------

Resolving deltas: 100% (240/240), done.
::: Changing rights of backend folder
::: Starting packages installation with npm
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> uws@9.14.0 install /home/kupiki/Kupiki-Hotspot-Admin-Backend/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> sqlite3@4.0.2 install /home/kupiki/Kupiki-Hotspot-Admin-Backend/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.2/node-v57-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.2 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/kupiki/Kupiki-Hotspot-Admin-Backend/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3240000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o
::: 
::: Something went wrong with the last command. Please check the log file

**Comment by pihomeserver** [comment]
Can you try this `su - kupiki -c "cd /home/kupiki/Kupiki-Hotspot-Admin-Backend && npm clean && npm install"`?

**Comment by EasyVoiceTel** [comment]
It says;

pi@EasyVoiceTelecom-Hotspot:/ $ su - kupiki -c "cd /home/kupiki/Kupiki-Hotspot-Admin-Backend && npm clean && npm install"
Password: 
su: Authentication failure

Whoops didn't mean to spam but it look like the txt didn't paste...

**Comment by pihomeserver** [comment]
You have to be root to perform the install and the command as it uses the kupiki user that has no password

**Comment by EasyVoiceTel** [comment]
Okay ill try it later

**Comment by EasyVoiceTel** [comment]
please delete topic since there is nothing useful here 👍
