### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by fabien321** [Kupiki/Kupiki-Hotspot-Admin-Install#5]
Hello,

Is an update planned?

cordially

**Comment by pihomeserver** [comment]
Hello
Update for ? Do you have issues on install ?

**Comment by fabien321** [comment]
yes errors to the installation, and when I want to connect, he tells me that the login and password are incorrect.

![image](https://user-images.githubusercontent.com/8382617/46724645-bc2de180-cc7a-11e8-8fd1-85aa471ee837.png)


![image](https://user-images.githubusercontent.com/8382617/46724895-41b19180-cc7b-11e8-870d-8c206cfefcf2.png)

**Comment by pihomeserver** [comment]
It's not errors but warning with no impact on the process.
Did you check pm2 logs in the kupiki user folder ? In particular the backend one where i guess there is an error with the database where the admin user is created

**Comment by fabien321** [comment]
I finished the reinstallation and I send you the logs

**Comment by pihomeserver** [comment]
Did you also look at issue #2 ?

**Comment by pihomeserver** [comment]
If logs are pictures in your post, that's not logs (and not even errors). Look first at issue #2 about how to search for information. 
Keep in mind that this repo is in an early release with all related bugs that could come with

**Comment by fabien321** [comment]
I do not see the base kupiki.sqlite in the backend folder

**Comment by fabien321** [comment]
![image](https://user-images.githubusercontent.com/8382617/46728996-69592780-cc84-11e8-8fcf-d09950c7a530.png)

**Comment by pihomeserver** [comment]
The SQLite file location is set in the configuration JSON of the backend with a default value set to /var/local/kupiki/kupiki.sqlite
Please check if the access to the folder is possible for the user kupiki (read and write). It should create the file if it's missing and populate the database with the default user

**Comment by fabien321** [comment]
![image](https://user-images.githubusercontent.com/8382617/46729543-ec2eb200-cc85-11e8-93e5-a1f1308d6d18.png)


my var / local is empty, it's probably the problem

**Comment by pihomeserver** [comment]
Yes. Create the folder kupiki with either 777 rights or better if you want to secure all with read access for all and write access only to kupiki user
Then restart the pm2 backlog or reboot the pi and test again

**Comment by fabien321** [comment]
yes, it works
