### ISSUE TITLE
After changed Host Ip - CORS error  appears

### ISSUE THREAD

**Issue by mali44** [Kupiki/Kupiki-Hotspot-Admin-Install#6]
Access to XMLHttpRequest at 'http://10.42.0.185:4000/api/auth/login' from origin 'http://10.42.0.185:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://192.168.137.130:3000' that is not equal to the supplied origin.

**Comment by mali44** [comment]
Oh I forgot to edit kupiki/Kupiki-Hotspot-Admin-Backend/src/config.json file. That works fine now . Thank you

**Comment by pihomeserver** [comment]
Thanks @mali44
Good to know it works but you should not have to do it manually ! I will check that in the script
