### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by BenoitEirik** [Kupiki/Kupiki-Hotspot-Admin-Install#7]
Hello. I have a problem about installation but I don't know why. I give you that:

'pi@raspberrypi:~/Kupiki-Hotspot-Script $ sudo chmod +x pihotspot.sh && sudo ./pihotspot.sh
:::
::: You are root - OK
::: Checking for updater
::: Updater already exists. It will auto update itself
::: Checking for existing cron job
::: Checking HOTSPOT_NETWORK and HOTSPOT_IP parameters : OK
::: Checking that HOTSPOT_IP is not the same than the WAN_INTERFACE : OK
::: Checking that HOTSPOT_NETWORK is not the same than the WAN_INTERFACE network : OK
:::
::: Verifying free disk space (1024 Mb) - OK
::: :::
::: ::: Configure sysctl kernel parameters
::: :::
::: Preparing log file
::: Log file already exists. Creating a backup.
::: 
::: Creating the log file
::: 
::: Log file created : /var/log/kupiki_hotspot.log
::: Use command 'tail -f /var/log/kupiki_hotspot.log' in a new console to get installation details
::: Updating APT config to force IPv4
::: Configuring localepurge
::: Updating packages list
:::
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-Hotspot installation...
::: Disable integrated Bluetooth support (After next reboot)
::: Remove old configuration of Coova Chilli
::: Remove old configuration of haserl
::: Remove old configuration of hostapd
::: Checking for tun module
::: Insert tun module if existing (for Raspbian Jessie Lite)
::: Modprobe module (no check - useless if already loaded)
::: Checking for tun module
::: Checking if LAN interface already exists
::: Adding MariaDb password
::: Adding MariaDb password (confirmation)
::: Getting WAN IP of the Raspberry Pi (for daloradius access)
::: Updating the system hostname to Saint Joseph Des Glycines
::: Adding Avahi dependencies
::: Updating /etc/hosts
::: Correct configuration for Collectd daemon
::: Install Docker
# Executing docker install script, commit: f45d7c11389849ff46a6b4d94e0dd1ffebca32c1
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Fri Oct 18 16:03:00 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Fri Oct 18 15:56:55 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
id: ‘kupiki’: no such user
::: Create dedicated user kupiki
Adding user `kupiki' ...
Adding new group `kupiki' (1001) ...
Adding new user `kupiki' (1001) with group `kupiki' ...
Creating home directory `/home/kupiki' ...
Copying files from `/etc/skel' ...
::: Add user kupiki to docker group
Adding user kupiki to group docker
::: Install pika module
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pika
  Downloading https://files.pythonhosted.org/packages/a1/ae/8bedf0e9f1c0c5d046db3a7428a4227fe36ec1b8e25607f3c38ac9bf513c/pika-1.1.0-py2.py3-none-any.whl (148kB)
    100% |████████████████████████████████| 153kB 932kB/s 
Installing collected packages: pika
Successfully installed pika-1.1.0
::: Install docker-compose
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting docker-compose~=1.23.0
  Downloading https://files.pythonhosted.org/packages/1e/6c/bf9879305530c4b765ef4eb3be76202788ca1037aec74d2c0ec73191d467/docker_compose-1.23.2-py2.py3-none-any.whl (131kB)
    100% |████████████████████████████████| 133kB 414kB/s 
Requirement already satisfied: six<2,>=1.3.0 in /usr/lib/python2.7/dist-packages (from docker-compose~=1.23.0) (1.12.0)
Collecting backports.ssl-match-hostname>=3.5; python_version < "3.5" (from docker-compose~=1.23.0)
  Downloading https://www.piwheels.org/simple/backports-ssl-match-hostname/backports.ssl_match_hostname-3.7.0.1-py2.py3-none-any.whl
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from docker-compose~=1.23.0) (1.0.17)
Collecting requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 906kB/s 
Collecting PyYAML<4,>=3.10 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 656kB/s 
Collecting docker<4.0,>=3.6.0 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/09/da/7cc7ecdcd01145e9924a8ccbe9c1baf3a362fc75d4cb150676eb5231ea60/docker-3.7.3-py2.py3-none-any.whl (134kB)
    100% |████████████████████████████████| 143kB 641kB/s 
Collecting jsonschema<3,>=2.5.1 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting docopt<0.7,>=0.6.1 (from docker-compose~=1.23.0)
  Downloading https://www.piwheels.org/simple/docopt/docopt-0.6.2-py2.py3-none-any.whl
Collecting cached-property<2,>=1.2.0 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Collecting websocket-client<1.0,>=0.32.0 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 770kB/s 
Requirement already satisfied: enum34<2,>=1.0.4; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from docker-compose~=1.23.0) (1.1.6)
Collecting dockerpty<0.5,>=0.4.1 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz
Collecting texttable<0.10,>=0.9.0 (from docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/02/e1/2565e6b842de7945af0555167d33acfc8a615584ef7abd30d1eae00a4d80/texttable-0.9.1.tar.gz
Collecting chardet<3.1.0,>=3.0.2 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 850kB/s 
Collecting certifi>=2017.4.17 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 824kB/s 
Collecting urllib3<1.25,>=1.21.1 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/01/11/525b02e4acc0c747de8b6ccdab376331597c569c42ea66ab0a1dbd36eca2/urllib3-1.24.3-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 963kB/s 
Collecting idna<2.8,>=2.5 (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 1.5MB/s 
Collecting docker-pycreds>=0.4.0 (from docker<4.0,>=3.6.0->docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl
Collecting functools32; python_version == "2.7" (from jsonschema<3,>=2.5.1->docker-compose~=1.23.0)
  Downloading https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
Building wheels for collected packages: PyYAML, dockerpty, texttable, functools32
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /root/.cache/pip/wheels/ad/da/0c/74eb680767247273e2cf2723482cb9c924fe70af57c334513f
  Running setup.py bdist_wheel for dockerpty ... done
  Stored in directory: /root/.cache/pip/wheels/e5/1e/86/bd0a97a0907c6c654af654d5875d1d4383dd1f575f77cee4aa
  Running setup.py bdist_wheel for texttable ... done
  Stored in directory: /root/.cache/pip/wheels/99/1e/2b/8452d3a48dad98632787556a0f2f90d56703b39cdf7d142dd1
  Running setup.py bdist_wheel for functools32 ... done
  Stored in directory: /root/.cache/pip/wheels/b5/18/32/77a1030457155606ba5e3ec3a8a57132b1a04b1c4f765177b2
Successfully built PyYAML dockerpty texttable functools32
Installing collected packages: backports.ssl-match-hostname, chardet, certifi, urllib3, idna, requests, PyYAML, websocket-client, docker-pycreds, docker, functools32, jsonschema, docopt, cached-property, dockerpty, texttable, docker-compose
Successfully installed PyYAML-3.13 backports.ssl-match-hostname-3.7.0.1 cached-property-1.5.1 certifi-2019.9.11 chardet-3.0.4 docker-3.7.3 docker-compose-1.23.2 docker-pycreds-0.4.0 dockerpty-0.4.1 docopt-0.6.2 functools32-3.2.3.post2 idna-2.7 jsonschema-2.6.0 requests-2.20.1 texttable-0.9.1 urllib3-1.24.3 websocket-client-0.56.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nfdump is already the newest version (1.6.17-1).
The following NEW packages will be installed:
  fprobe
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 27,8 kB of archives.
After this operation, 75,8 kB of additional disk space will be used.
Get:1 http://ftp.igh.cnrs.fr/pub/os/linux/raspbian/raspbian buster/main armhf fprobe armhf 1.1-8 [27,8 kB]
Fetched 27,8 kB in 1s (44,5 kB/s) 
Preconfiguring packages ...
Selecting previously unselected package fprobe.
(Reading database ... 62564 files and directories currently installed.)
Preparing to unpack .../fprobe_1.1-8_armhf.deb ...
Unpacking fprobe (1.1-8) ...
Setting up fprobe (1.1-8) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for systemd (241-7~deb10u1+rpi1) ...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-Hotspot installation...
:::
::: Removing any previous sources of CoovaChilli project
::: Cloning CoovaChilli project
::: Removing any previous sources of Kupiki Admin
::: Cloning Kupiki Admin web UI project
::: Download Kupiki SQL Counters
::: Download Haserl
::: Cloning daloradius project
::: Cloning Pi Hotspot portal project
::: Cloning Pi Hotspot portal backend project
::: Starting MySql service
::: Update interface configuration (eth0)
::: Update interface configuration (wlan0)
::: Update wifi configuration to add country code
::: Activating the WAN interface
::: Activating the LAN interface
::: Stopping fprobe service
::: Stopping nfdump service
::: Updating fprobe configuration
::: Updating nfdump configuration
::: Updating nfdump service configuration (init.d)
::: Updating nfdump service configuration (systemd)
::: Set cleaning options for Netflow data
Force rebuild to create stat record in /var/cache/nfdump
Scanning files in /var/cache/nfdump .. done.
Expired files:      0
Expired file size:  0 B
Expired time range: 0 sec

First:     2019-10-20 21:04:00
Last:      2019-10-20 21:04:00
Lifetime:  0 sec
Numfiles:  1
Filesize:  4096 = 4.0 KB
Max Size:  <none>
Max Life:  31536000 = 52.1 weeks
Watermark: 95%
Status:    OK
::: Adding logs cleaning every day at 1am (system time)
::: Adding Netflow stats update in the crontab
::: Stopping freeradius service to update the configuration
::: Creating freeradius database
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'radius'@'localhost'
::: Installing freeradius schema
::: Adding setup data
::: Updating freeradius configuration - Activate SQL support
::: Configuration of the Freeradius SQL driver
::: Change dialect of the Freeradius SQL driver to mysql
::: Configuration of the Freeradius SQL connection
::: Updating freeradius configuration - Activate SQL counters
::: Bug fix for SQL dialect once SQL Counters are activated
::: Update of Freeradius secret key
::: Updating inner-tunnel configuration (1)
::: Updating inner-tunnel configuration (2)
::: Updating freeradius default configuration (1)
::: Updating freeradius default configuration (2)
::: Activating COA support in Freeradius
::: Adding CoovaChilli counters (limit bandwidth)
::: Updating file access rights
::: Activating counters
::: Checking freeradius configuration
::: Activating IP forwarding
::: Restarting network service to take IP forwarding into account
::: Building CoovaChilli package
::: Installing CoovaChilli package
::: Configuring CoovaChilli up action
::: Block access from LAN to WAN except portal
::: Activating CoovaChilli
::: Creating CoovaChilli at /etc/chilli/config
::: Activating CoovaChilli on boot
::: Uncompressing Haserl archive
::: Compiling and installing Haserl
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for working memcmp... yes
checking for memset... yes
checking for putenv... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strncasecmp... yes
checking for strstr... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating src/config.h
config.status: executing depfiles commands

** Configuration summary for haserl 0.9.35:

	Building haserl with with lua disabled
	Building haserl with with bash-extensions disabled
	libs: 

Making all in src
make[1]: Entering directory '/usr/src/haserl-0.9.35/src'
make  all-am
make[2]: Entering directory '/usr/src/haserl-0.9.35/src'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-common.o -MD -MP -MF .deps/haserl-common.Tpo -c -o haserl-common.o `test -f 'common.c' || echo './'`common.c
mv -f .deps/haserl-common.Tpo .deps/haserl-common.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-sliding_buffer.o -MD -MP -MF .deps/haserl-sliding_buffer.Tpo -c -o haserl-sliding_buffer.o `test -f 'sliding_buffer.c' || echo './'`sliding_buffer.c
mv -f .deps/haserl-sliding_buffer.Tpo .deps/haserl-sliding_buffer.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-h_error.o -MD -MP -MF .deps/haserl-h_error.Tpo -c -o haserl-h_error.o `test -f 'h_error.c' || echo './'`h_error.c
mv -f .deps/haserl-h_error.Tpo .deps/haserl-h_error.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-h_script.o -MD -MP -MF .deps/haserl-h_script.Tpo -c -o haserl-h_script.o `test -f 'h_script.c' || echo './'`h_script.c
mv -f .deps/haserl-h_script.Tpo .deps/haserl-h_script.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-rfc2388.o -MD -MP -MF .deps/haserl-rfc2388.Tpo -c -o haserl-rfc2388.o `test -f 'rfc2388.c' || echo './'`rfc2388.c
mv -f .deps/haserl-rfc2388.Tpo .deps/haserl-rfc2388.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-h_bash.o -MD -MP -MF .deps/haserl-h_bash.Tpo -c -o haserl-h_bash.o `test -f 'h_bash.c' || echo './'`h_bash.c
mv -f .deps/haserl-h_bash.Tpo .deps/haserl-h_bash.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT haserl-haserl.o -MD -MP -MF .deps/haserl-haserl.Tpo -c -o haserl-haserl.o `test -f 'haserl.c' || echo './'`haserl.c
haserl.c: In function ‘myputenv’:
haserl.c:249:7: warning: ‘strncat’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
       strncat (entry, prefix, strlen (prefix));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
haserl.c:249:7: warning: ‘strncat’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
mv -f .deps/haserl-haserl.Tpo .deps/haserl-haserl.Po
gcc  -g -O2 -Wall   -o haserl haserl-common.o haserl-sliding_buffer.o haserl-h_error.o haserl-h_script.o haserl-rfc2388.o haserl-h_bash.o  haserl-haserl.o   
make[2]: Leaving directory '/usr/src/haserl-0.9.35/src'
make[1]: Leaving directory '/usr/src/haserl-0.9.35/src'
Making all in doc
make[1]: Entering directory '/usr/src/haserl-0.9.35/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/src/haserl-0.9.35/doc'
make[1]: Entering directory '/usr/src/haserl-0.9.35'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/usr/src/haserl-0.9.35'
::: Updating chilli configuration
::: Creating configuration file for hostapd
::: Configuring hostapd
::: Installing Daloradius in Nginx folder
::: Loading daloradius configuration into MySql
::: Drop freeradius tables created by Daloradius to reload the Freeradius 3.0 version
::: Reload original Freeradius schema
::: Creating users privileges for localhost
::: Granting users privileges
::: Configuring daloradius DB user name
::: Configuring daloradius DB user password
::: Configuring daloradius DB proxy configuration file
sed: can't read check_returned_code: No such file or directory
sed: can't read 0: No such file or directory
::: Configuring daloradius DB proxy path
::: Building NGINX configuration (default listen port : 80)
::: Building NGINX configuration for the portal (default listen port : 443)
::: Creating folder for Nginx certificates
::: Generating self-signed certificate
req: Use -help for summary.
::: 
::: Something went wrong with the last command. Please check the log file
::: 
'

Thank you for your help.

**Comment by pihomeserver** [comment]
Please fill the template when you open an issue. We need to know parameters used
I see you activated the HTTPS but for now there is a bug with it. Update is in progress

**Comment by BenoitEirik** [comment]
Okay, thank you for your help. Now I have a new problem with Docker. I have a raspberry pi 3B+ and raspbian.

`:::
::: You are root - OK
::: A previous installation has been done. It's not recommanded to execute more than once the script.
Are you sure (Y/N) ?Y
::: Checking for updater
::: Updater already exists. It will auto update itself
::: Checking for existing cron job
::: Checking HOTSPOT_NETWORK and HOTSPOT_IP parameters : OK
::: Checking that HOTSPOT_IP is not the same than the WAN_INTERFACE : OK
::: Checking that HOTSPOT_NETWORK is not the same than the WAN_INTERFACE network : OK
:::
::: Verifying free disk space (1024 Mb) - OK
::: :::
::: ::: Configure sysctl kernel parameters
::: :::
::: Preparing log file
::: Log file already exists. Creating a backup.
::: 
::: Creating the log file
::: 
::: Log file created : /var/log/kupiki_hotspot.log
::: Use command 'tail -f /var/log/kupiki_hotspot.log' in a new console to get installation details
::: Updating APT config to force IPv4
::: Configuring localepurge
::: Updating packages list
:::
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 2 updates available for your system!
:::
::: Upgrading the packages. Please be patient.
::: Disable integrated Bluetooth support (After next reboot)
::: Remove old configuration of Coova Chilli
::: Remove old configuration of haserl
::: Remove old configuration of hostapd
::: Checking for tun module
::: Checking if LAN interface already exists
::: Adding MariaDb password
::: Adding MariaDb password (confirmation)
::: Getting WAN IP of the Raspberry Pi (for daloradius access)
::: Updating the system hostname to Saint Joseph Des Glycines
::: Adding Avahi dependencies
::: Updating /etc/hosts
::: Correct configuration for Collectd daemon
docker is /usr/bin/docker
::: Install pika module
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pika in /usr/local/lib/python2.7/dist-packages (1.1.0)
docker-compose is /usr/local/bin/docker-compose
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fprobe is already the newest version (1.1-8).
nfdump is already the newest version (1.6.17-1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with Pi-Hotspot installation...
:::
::: Removing any previous sources of CoovaChilli project
::: Cloning CoovaChilli project
::: Removing any previous sources of Kupiki Admin
::: Cloning Kupiki Admin web UI project
::: Download Kupiki SQL Counters
::: Download Haserl
::: Cloning daloradius project
::: Cloning Pi Hotspot portal project
::: Cloning Pi Hotspot portal backend project
::: Starting MySql service
::: Update interface configuration (eth0)
::: Update interface configuration (wlan0)
::: Update wifi configuration to add country code
::: Activating the WAN interface
::: Activating the LAN interface
::: Stopping fprobe service
::: Stopping nfdump service
::: Updating fprobe configuration
::: Updating nfdump configuration
::: Updating nfdump service configuration (init.d)
::: Updating nfdump service configuration (systemd)
::: Set cleaning options for Netflow data
Expired files:      0
Expired file size:  0 B
Expired time range: 0 sec

First:     2019-10-20 21:04:00
Last:      2019-10-22 04:32:00
Lifetime:  113280 = 1.3 days
Numfiles:  115
Filesize:  471040 = 460.0 KB
Max Size:  <none>
Max Life:  31536000 = 52.1 weeks
Watermark: 95%
Status:    OK
::: Adding logs cleaning every day at 1am (system time)
::: Adding Netflow stats update in the crontab
::: Stopping freeradius service to update the configuration
::: Creating freeradius database
::: Installing freeradius schema
::: Adding setup data
::: Updating freeradius configuration - Activate SQL support
::: Configuration of the Freeradius SQL driver
::: Change dialect of the Freeradius SQL driver to mysql
::: Configuration of the Freeradius SQL connection
::: Updating freeradius configuration - Activate SQL counters
::: Bug fix for SQL dialect once SQL Counters are activated
::: Update of Freeradius secret key
::: Updating inner-tunnel configuration (1)
::: Updating inner-tunnel configuration (2)
::: Updating freeradius default configuration (1)
::: Updating freeradius default configuration (2)
::: Activating COA support in Freeradius
::: Adding CoovaChilli counters (limit bandwidth)
::: Updating file access rights
::: Activating counters
::: Checking freeradius configuration
::: Activating IP forwarding
::: Restarting network service to take IP forwarding into account
::: Building CoovaChilli package
::: Installing CoovaChilli package
::: Configuring CoovaChilli up action
::: Block access from LAN to WAN except portal
::: Activating CoovaChilli
::: Creating CoovaChilli at /etc/chilli/config
::: Activating CoovaChilli on boot
::: Uncompressing Haserl archive
::: Compiling and installing Haserl
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether ln -s works... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for working memcmp... yes
checking for memset... yes
checking for putenv... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strncasecmp... yes
checking for strstr... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands

** Configuration summary for haserl 0.9.35:

	Building haserl with with lua disabled
	Building haserl with with bash-extensions disabled
	libs: 

Making all in src
make[1]: Entering directory '/usr/src/haserl-0.9.35/src'
make  all-am
make[2]: Entering directory '/usr/src/haserl-0.9.35/src'
make[2]: Leaving directory '/usr/src/haserl-0.9.35/src'
make[1]: Leaving directory '/usr/src/haserl-0.9.35/src'
Making all in doc
make[1]: Entering directory '/usr/src/haserl-0.9.35/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/usr/src/haserl-0.9.35/doc'
make[1]: Entering directory '/usr/src/haserl-0.9.35'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/usr/src/haserl-0.9.35'
::: Updating chilli configuration
::: Creating configuration file for hostapd
::: Configuring hostapd
::: Installing Daloradius in Nginx folder
::: Loading daloradius configuration into MySql
::: Drop freeradius tables created by Daloradius to reload the Freeradius 3.0 version
::: Reload original Freeradius schema
::: Creating users privileges for localhost
::: Granting users privileges
::: Configuring daloradius DB user name
::: Configuring daloradius DB user password
::: Configuring daloradius DB proxy configuration file
sed: can't read check_returned_code: No such file or directory
sed: can't read 0: No such file or directory
::: Configuring daloradius DB proxy path
::: Building NGINX configuration (default listen port : 80)
::: Building NGINX configuration for the portal (default listen port : 80)
::: Activating portal website
::: Installing the portal in Nginx folder
::: Updating Captive Portal configuration file - Register host
::: Updating Captive Portal configuration file - Chilli Controller host
::: Checking Nginx configuration file
::: Installing the portal backend in the user kupiki home folder
::: Updating Captive Portal backend configuration file
::: Update rights for NGINX sites
::: 
::: Build the Docker image of Portal backend
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
::: 
::: Something went wrong with the last command. Please check the log file
::: `

**Comment by pihomeserver** [comment]
Patch also in progress
Remove docker & docker compose using pip and reinstall them using apt

**Comment by pihomeserver** [comment]
Please use the right repo for issues (your are in the frontend install, not the script) and format the text to make it more readable
